#version: '3.0'
#
#services:
#
#  localstack:
#    image: localstack/localstack:latest
#    environment:
#      - AWS_DEFAULT_REGION=eu-west-3
#      - EDGE_PORT=4566
#      - SERVICES=sqs,sns
#    ports:
#      - '4566:4566'

version: "3.0"
services:
    localstack:
      image: localstack/localstack
      container_name: localstack
      ports:
        - "4566:4566"
        - "9000:9000"
      environment:
        - SERVICES=sqs,dynamodb,sns
        - DEFAULT_REGION=eu-central-1
        - DATA_DIR=/tmp/localstack/data
        - PORT_WEB_UI=9000
        - LAMBDA_EXECUTOR=local
        - DOCKER_HOST=unix:///var/run/docker.sock
        - START_WEB=1
      volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"